# Databricks notebook source
# MAGIC %md
# MAGIC # Synthetic scale manifest — canonical rows → logical samples
# MAGIC
# MAGIC This notebook is deliberately **synthetic-only**. It never parses a gVCF. Instead, it
# MAGIC reads dosage and ancestry already extracted for each canonical `source_sample_id`, then
# MAGIC fans those rows out to logical sample IDs from a Delta manifest. This measures the
# MAGIC sample-cardinality path (Delta writes, reconcile, scoring, and MERGE) without pretending
# MAGIC that one physical gVCF represents 100k independent extraction reads.

# COMMAND ----------

dbutils.widgets.text("catalog", "genesis_workbench", "Catalog")
dbutils.widgets.text("schema", "genesis_schema", "Schema")
dbutils.widgets.text("sample_manifest_path", "", "Delta manifest generated by prep_scale_manifest")
dbutils.widgets.text("confirm_synthetic_fanout", "false", "Must be true: manifest aliases are synthetic")
dbutils.widgets.text("fanout_batch_size", "25", "Maximum logical samples per atomic staging batch")
dbutils.widgets.text("max_fanout_rows", "1000000000", "Refuse larger dosage fan-out unless confirm_large=true")
dbutils.widgets.text("confirm_large", "false", "Explicitly allow estimated rows above max_fanout_rows")
dbutils.widgets.text("target_rows_per_file", "2000000", "Approximate dosage rows per output partition")
dbutils.widgets.text("fanout_staging_root", "", "Optional staging root; defaults beside manifest")

catalog = dbutils.widgets.get("catalog").strip()
schema = dbutils.widgets.get("schema").strip()
manifest_path = dbutils.widgets.get("sample_manifest_path").strip().rstrip("/")
confirm_synthetic = dbutils.widgets.get("confirm_synthetic_fanout").strip().lower() == "true"
fanout_batch_size = int(dbutils.widgets.get("fanout_batch_size"))
max_fanout_rows = int(dbutils.widgets.get("max_fanout_rows"))
confirm_large = dbutils.widgets.get("confirm_large").strip().lower() == "true"
target_rows_per_file = int(dbutils.widgets.get("target_rows_per_file"))
staging_root = dbutils.widgets.get("fanout_staging_root").strip().rstrip("/")

if not manifest_path:
    dbutils.notebook.exit("0 — sample_manifest_path empty; synthetic fan-out disabled")
if not confirm_synthetic:
    raise ValueError(
        "sample_manifest_path was supplied but confirm_synthetic_fanout=false. "
        "These aliases are a scale-test construct, not production identities."
    )
if fanout_batch_size < 1:
    raise ValueError("fanout_batch_size must be >= 1")
if max_fanout_rows < 1:
    raise ValueError("max_fanout_rows must be >= 1")
if target_rows_per_file < 1:
    raise ValueError("target_rows_per_file must be >= 1")

spark.sql(f"USE CATALOG {catalog}")
spark.sql(f"USE SCHEMA {schema}")

# COMMAND ----------

import math
from delta.tables import DeltaTable
import pyspark.sql.functions as F

manifest = spark.read.format("delta").load(manifest_path)
required = {
    "sample_id", "source_sample_id", "vcf_path", "source_fingerprint",
    "synthetic", "scale_run_id", "batch_id",
}
missing = required - set(manifest.columns)
if missing:
    raise ValueError(f"manifest missing required columns: {sorted(missing)}")

manifest = manifest.select(*sorted(required)).cache()
n_manifest = manifest.count()
if n_manifest == 0:
    raise ValueError("manifest is empty")
if manifest.where(~F.col("synthetic")).limit(1).count():
    raise ValueError("manifest contains synthetic=false rows; production fan-out is forbidden")
if manifest.where(
    F.col("sample_id").isNull()
    | (F.trim("sample_id") == "")
    | F.col("source_sample_id").isNull()
    | (F.trim("source_sample_id") == "")
).limit(1).count():
    raise ValueError("manifest sample_id/source_sample_id must be non-empty")
if manifest.groupBy("sample_id").count().where(F.col("count") != 1).limit(1).count():
    raise ValueError("manifest sample_id values must be unique")
oversized_batch = (
    manifest.groupBy("batch_id").count().where(F.col("count") > fanout_batch_size).limit(1)
)
if oversized_batch.count():
    row = oversized_batch.first()
    raise ValueError(
        f"manifest batch {row['batch_id']} has {row['count']} samples, above "
        f"fanout_batch_size={fanout_batch_size}. Regenerate with a smaller batch_size "
        "or raise the bound explicitly for a thinned-loci run."
    )
if manifest.where(F.col("sample_id") == F.col("source_sample_id")).limit(1).count():
    raise ValueError("synthetic sample_id must differ from source_sample_id")
if manifest.select("scale_run_id").distinct().count() != 1:
    raise ValueError("one materialization run accepts exactly one scale_run_id")
if manifest.groupBy("source_sample_id").agg(
    F.countDistinct("vcf_path").alias("n_paths"),
    F.countDistinct("source_fingerprint").alias("n_fingerprints"),
).where((F.col("n_paths") != 1) | (F.col("n_fingerprints") != 1)).limit(1).count():
    raise ValueError("each source_sample_id must map to one physical path and fingerprint")

scale_run_id = manifest.select("scale_run_id").first()["scale_run_id"]
if not staging_root:
    staging_root = manifest_path + "_staging"
print(f"manifest: {n_manifest:,} logical sample(s), scale_run_id={scale_run_id}")
print(f"staging: {staging_root}")

# COMMAND ----------

# The ledger is audit/control metadata. Target MERGEs remain the source of idempotency:
# a failed MERGE is atomic, while a successful retry finds the same keys already present.
spark.sql("""
CREATE TABLE IF NOT EXISTS synthetic_fanout_ledger (
  scale_run_id STRING,
  batch_id STRING,
  phase STRING,
  source_fingerprint STRING,
  n_samples BIGINT,
  n_rows BIGINT,
  status STRING,
  completed_at TIMESTAMP
) USING DELTA
""")
spark.sql(
    "ALTER TABLE synthetic_fanout_ledger SET TBLPROPERTIES "
    "('data_classification' = 'SYNTHETIC_TEST_METADATA')"
)

if not spark.catalog.tableExists("dosage"):
    raise ValueError("dosage table is missing; extract each canonical source gVCF first")
if not spark.catalog.tableExists("sample_ancestry"):
    raise ValueError("sample_ancestry table is missing; classify each canonical source gVCF first")

sources = manifest.select("source_sample_id").distinct()
missing_dose_sources = sources.join(
    spark.table("dosage").select(F.col("sample_id").alias("source_sample_id")).distinct(),
    "source_sample_id",
    "left_anti",
)
missing_anc_sources = sources.join(
    spark.table("sample_ancestry").select(F.col("sample_id").alias("source_sample_id")).distinct(),
    "source_sample_id",
    "left_anti",
)
if missing_dose_sources.limit(1).count():
    raise ValueError(
        "canonical dosage is missing for source sample(s): "
        f"{[r['source_sample_id'] for r in missing_dose_sources.limit(20).collect()]}"
    )
if missing_anc_sources.limit(1).count():
    raise ValueError(
        "canonical ancestry is missing for source sample(s): "
        f"{[r['source_sample_id'] for r in missing_anc_sources.limit(20).collect()]}"
    )

# Determine pending IDs in Spark. Never collect cohort IDs to the driver.
dose_have = spark.table("dosage").select("sample_id").distinct()
anc_have = spark.table("sample_ancestry").select("sample_id").distinct()
dose_pending = manifest.join(dose_have, "sample_id", "left_anti").cache()
anc_pending = manifest.join(anc_have, "sample_id", "left_anti").cache()
n_dose_pending = dose_pending.count()
n_anc_pending = anc_pending.count()

# Exact row estimate from canonical dosage cardinality × pending aliases per source.
source_counts = (
    spark.table("dosage")
    .join(F.broadcast(sources), F.col("sample_id") == F.col("source_sample_id"), "inner")
    .groupBy("source_sample_id")
    .agg(F.count(F.lit(1)).alias("canonical_rows"))
).cache()
source_counts.count()  # materialize once; reused for the global estimate and every batch
pending_counts = dose_pending.groupBy("source_sample_id").agg(
    F.count(F.lit(1)).alias("pending_aliases")
)
estimated_rows = (
    source_counts.join(pending_counts, "source_sample_id", "inner")
    .select(F.sum(F.col("canonical_rows") * F.col("pending_aliases")).alias("n"))
    .first()["n"]
    or 0
)
print(
    f"pending: dosage={n_dose_pending:,}, ancestry={n_anc_pending:,}; "
    f"estimated dosage rows={estimated_rows:,}"
)
if estimated_rows > max_fanout_rows and not confirm_large:
    raise ValueError(
        f"estimated fan-out {estimated_rows:,} rows exceeds max_fanout_rows={max_fanout_rows:,}. "
        "Inspect storage/cost, then set confirm_large=true explicitly."
    )

# COMMAND ----------

def _record_batch(batch_df, batch_id, phase, n_rows):
    """Upsert one completed phase into the audit ledger."""
    summary = (
        batch_df.agg(
            F.first("scale_run_id").alias("scale_run_id"),
            F.first("source_fingerprint").alias("source_fingerprint"),
            F.count(F.lit(1)).alias("n_samples"),
        )
        .withColumn("batch_id", F.lit(str(batch_id)))
        .withColumn("phase", F.lit(phase))
        .withColumn("n_rows", F.lit(int(n_rows)).cast("long"))
        .withColumn("status", F.lit("COMPLETE"))
        .withColumn("completed_at", F.current_timestamp())
    )
    (
        DeltaTable.forName(spark, f"{catalog}.{schema}.synthetic_fanout_ledger")
        .alias("t")
        .merge(
            summary.alias("s"),
            "t.scale_run_id = s.scale_run_id AND t.batch_id = s.batch_id AND t.phase = s.phase",
        )
        .whenMatchedUpdateAll()
        .whenNotMatchedInsertAll()
        .execute()
    )


def _materialize_dosage_batch(batch_df, batch_id):
    n_samples = batch_df.count()
    if n_samples == 0:
        return 0
    src = spark.table("dosage").alias("d")
    aliases = F.broadcast(
        batch_df.select("sample_id", "source_sample_id", "source_fingerprint")
    ).alias("m")
    out = (
        src.join(aliases, F.col("d.sample_id") == F.col("m.source_sample_id"), "inner")
        .select(F.col("m.sample_id").alias("sample_id"), F.col("d.variant_id"), F.col("d.dose"))
    )
    canonical_rows = (
        source_counts.join(
            batch_df.groupBy("source_sample_id").count(),
            "source_sample_id",
            "inner",
        )
        .select(F.sum(F.col("canonical_rows") * F.col("count")).alias("n"))
        .first()["n"]
        or 0
    )
    n_partitions = max(
        spark.sparkContext.defaultParallelism,
        int(math.ceil(canonical_rows / target_rows_per_file)),
    )
    stage_path = f"{staging_root}/dosage/batch_id={batch_id}"
    (
        out.repartition(n_partitions, "sample_id")
        .write.format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .save(stage_path)
    )
    staged = spark.read.format("delta").load(stage_path)
    (
        DeltaTable.forName(spark, f"{catalog}.{schema}.dosage")
        .alias("t")
        .merge(
            staged.alias("s"),
            "t.sample_id = s.sample_id AND t.variant_id = s.variant_id",
        )
        .whenNotMatchedInsertAll()
        .execute()
    )
    _record_batch(batch_df, batch_id, "dosage", canonical_rows)
    dbutils.fs.rm(stage_path, True)
    return canonical_rows


def _materialize_ancestry_batch(batch_df, batch_id):
    n_samples = batch_df.count()
    if n_samples == 0:
        return 0
    anc = spark.table("sample_ancestry")
    aliases = F.broadcast(
        batch_df.select("sample_id", "source_sample_id", "source_fingerprint")
    )
    payload_cols = [c for c in anc.columns if c != "sample_id"]
    out = (
        anc.alias("a")
        .join(aliases.alias("m"), F.col("a.sample_id") == F.col("m.source_sample_id"), "inner")
        .select(F.col("m.sample_id").alias("sample_id"), *[F.col(f"a.{c}") for c in payload_cols])
    )
    stage_path = f"{staging_root}/ancestry/batch_id={batch_id}"
    out.repartition(max(1, min(n_samples, spark.sparkContext.defaultParallelism))).write.format(
        "delta"
    ).mode("overwrite").option("overwriteSchema", "true").save(stage_path)
    staged = spark.read.format("delta").load(stage_path)
    (
        DeltaTable.forName(spark, f"{catalog}.{schema}.sample_ancestry")
        .alias("t")
        .merge(staged.alias("s"), "t.sample_id = s.sample_id")
        .whenNotMatchedInsertAll()
        .execute()
    )
    _record_batch(batch_df, batch_id, "ancestry", n_samples)
    dbutils.fs.rm(stage_path, True)
    return n_samples

# COMMAND ----------

# Batch IDs are small control metadata (100 batches for 100k samples at the default size).
batch_ids = [r["batch_id"] for r in manifest.select("batch_id").distinct().orderBy("batch_id").collect()]
total_dose_rows = 0
total_anc_rows = 0
for i, batch_id in enumerate(batch_ids, 1):
    dp = dose_pending.where(F.col("batch_id") == batch_id)
    ap = anc_pending.where(F.col("batch_id") == batch_id)
    print(f"[{i}/{len(batch_ids)}] batch_id={batch_id}")
    total_dose_rows += _materialize_dosage_batch(dp, batch_id)
    total_anc_rows += _materialize_ancestry_batch(ap, batch_id)

print(
    f"synthetic fan-out complete: scale_run_id={scale_run_id}; "
    f"dosage_rows={total_dose_rows:,}; ancestry_rows={total_anc_rows:,}"
)
dbutils.notebook.exit(
    f"scale_run_id={scale_run_id},dosage_rows={total_dose_rows},ancestry_rows={total_anc_rows}"
)
